name: Temp Get SSH Key
on:
  workflow_dispatch:
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write SSH key to file
        run: |
          echo "${{ secrets.OCI_SSH_PUBLIC_KEY }}" > ssh_pub_key.txt
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add ssh_pub_key.txt
          git commit -m "temp: store ssh pub key"
          git push
