name: Temp Get SSH Key
on:
  workflow_dispatch:
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key to artifact
        run: |
          mkdir -p /tmp/output
          printf '%s' "${{ secrets.OCI_SSH_PUBLIC_KEY }}" > /tmp/output/ssh_pub_key.txt
      - uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: /tmp/output/ssh_pub_key.txt
